experiment:
    project: "dynamic_tokenizer_generation"
    name: "gpt_quadtree_fixtree"
    # output_dir: "checkpoints/generator/debug"
    output_dir: "checkpoints/generator/gpt_quadtree_fixtree"
    max_train_examples: 1_281_167
    save_every: 10_000
    eval_every: 50_000
    generate_every: 1000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: False
    

tokenizer:
    type: "quadtok"
    tokenizer_ckpt_dir: "/mnt/ultracube/zec016/quadtok/vq_ckpts/tokenizer_ckpt.bin"
    vae_embed_dim: 8 # keep the same with "token_size" in "vq_model"


model:
    type: "quadtok"
    grad_checkpointing: True
    vq_model:
      quantize_mode: vq
      # vit arch
      vit_enc_model_size: "small"
      vit_dec_model_size: "small"
      vit_enc_patch_size: 16
      vit_dec_patch_size: 16
      decoder_token_size: 256
      codebook_size: 16384
      use_l2_norm: true
      commitment_cost: 0.25
      token_size: 8
    selector:
      token_size: 8
      num_patch_side_list: [1, 2, 4, 8, 16, 32] 
      patch_size_list: [16, 16, 16, 16, 16, 8]
    

    generator_type: "gpt-quadtree"

    generator:
        model_size: "base"
        patch_size: 1

        image_size: 256
        num_patch_side_list: [1, 2, 4, 8, 16, 32]
        patch_size_list: [16, 16, 16, 16, 16, 8]
        guaranteed_depth: 3  # All nodes with lod <= 3 are guaranteed to exist

        class_num: 1000
        label_drop_prob: 0.1

        mask_ratio_min: 0.7
        buffer_size: 1

        proj_dropout: 0.1
        attn_dropout: 0.1

        num_steps: 64
        randomize_temperature: 2.8
        guidance_scale: 1.0
        guidance_scale_pow: 3.0
        guidance_decay: "constant"

losses:
    model_embed_dim: 768
    diffloss_d: 8
    diffloss_w: 1280
    expand_loss_weight: 1.0


dataset:
    type: "simple_image"
    params:
        train_shards_path_or_url: "pipe:rclone cat hoss:jianglihan/data/imagenet/imagenet-train-{000000..000070}.tar"
        eval_shards_path_or_url: "pipe:rclone cat hoss:jianglihan/data/imagenet/imagenet-val-{000000..000049}.tar"
        num_workers_per_gpu: 4
    preprocessing:
        resize_shorter_edge: 256
        crop_size: 256
        random_crop: True
        random_flip: True
        res_ratio_filtering: True

optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.96
        weight_decay: 0.03


lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5


training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32 # 8 GPU, total batch size 1024
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 1000_000
    max_grad_norm: 1.0